---

########################################################################
# raspi-config
########################################################################

# See raspberrypi-wifi for wifi country code

# FIXME: Allow separate config of headless vs. GUI
rpicfg_memory_split: 16

# Enable VNC server.  '1' for disabled or '0' for enabled
rpicfg_disable_vnc_server: 1

# Enable SSH server.  '1' for disabled or '0' for enabled
# For almost all this situation, this should be set to enabled
rpicfg_disable_ssh_server: 0

# Boot behaviour
#  B1 - Console - Text console, requiring user to login
#  B2 - Console Autologin" "Text console, automatically logged in as 'pi' user
#  B3 - Desktop" "Desktop GUI, requiring user to login"
#  B4 - Desktop Autologin" "Desktop GUI, automatically logged in as 'pi' user"
#  Set to one of {B1|B2|B3|B4}
rpicfg_boot_behaviour: B1

# Enable I2C bus '1' for disabled or '0' for enabled
rpicfg_disable_i2c: 1
# Enable SPI bus '1' for disabled or '0' for enabled
rpicfg_disable_spi: 1

########################################################################

# WIFI - See group_vars/raspberrypi-wifi in inventory

# PACKAGES
always_update_cache: false
install_extra_packages: true

# Set to true to reboot
reboot_after_apt_upgrade: false

# If you want to install a bunch of developer tools, set this to true
install_developer_tools: false

install_developer_packages: true
install_python_developer_packages: true
install_pip_packages: true
install_nvm: true
install_npm_packages: true
install_npm_iot_cloud_packages: false
install_git_repositories: false

extra_packages_to_install:
  - dselect
  - screen
  - git
  - git-core
  - htop
  - curl
  - mosh
  - rcs
  - tcsh

developer_packages_to_install:
  - sysbench
  - wiringpi
  - python-pip
  - ruby-dev
  - python-dev
  - curl
  - git
  - autoconf
  - automake
  - build-essential
  - libssl-dev
  - emacs

python_developer_packages_to_install:
  - python-dev
  - python-pip
  - python-setuptools
  - python-setuptools-git
  - python3-pip
  - python3-dev
  - python3-setuptools
  - python3-setuptools-git

# pip_packages_to_install: [ awscli ]
pip_packages_to_install: []

nvm_versions:
  nvm: v0.33.8
  nvm_node: stable
  node_version: v9.3.0
  nvm_user: '{{ ansible_user }}'

npm_packages_to_install:
  - mqtt
  - crypto-js
  - minimist
  - websocket-stream

# npm_iot_cloud_packages_to_install: [ aws-iot-device-sdk ]
npm_iot_cloud_packages_to_install: []

git_repositories_basedir: /home/pi/projects

git_repositories_to_clone:
  - name: Iot Demo
    repo: https://github.com/idcrook/rpi-iot-demo-2017.git
    dest: "{{ git_repositories_basedir }}/iot-demo"
  - name: RGB slider
    repo: https://github.com/idcrook/rgb-slider.git
    dest: "{{ git_repositories_basedir }}/rgb-slider"
  - name: Pi Blaster
    repo: https://github.com/sarfata/pi-blaster.git
    dest: "{{ git_repositories_basedir }}/pi-blaster"
