---

# ansible seems unable to recognize jessie is systemd at the moment
# # ASSUME: systemd / jessie
# - name: Stop if non systemd OS type
#   assert:
#     that: ansible_service_mgr == "systemd"

- name: Configure options in /boot/config.txt.
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ raspberry_pi_boot_config_options }}"

# - name: Configure options in /etc/rc.local.
#   lineinfile:
#     dest: /etc/rc.local
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#     insertbefore: "^exit"
#     state: present
#   with_items: "{{ raspberry_pi_rc_local_options }}"

- include: apt-cacher-ng_client.yml
  when: apt_cacher_ng_proxy_address is defined

- name: raspi-config | Do some configuration
  include: raspi-config.yml

- name: Package maintenance | apt package maintenance
  include: apt-maintenance.yml

- name: Developer tasks
  include: developer.yml
  when: install_developer_tools is defined and install_developer_tools

# debug osx_say with something like
#   ansible all -i "localhost," -c local -m osx_say -a 'msg="Hello world" voice="Alex"'
# /usr/bin/say -v Alex hostname is all done
- osx_say:
    msg: '{{ inventory_hostname }} is all done'
    voice: Alex
  delegate_to: localhost
  become: no
