---

# Handy way to montior progress on remote machine:
#   sudo less  /var/log/apt/term.log
- name: Developer | Install developer packages
  apt: >
    pkg="{{ developer_packages_to_install }}" state=present
    update_cache={{ always_update_cache }} cache_valid_time=3600
  when: >
    install_developer_packages is defined
    and install_developer_packages

- name: Developer | Install python developer packages
  apt: >
    pkg="{{ python_developer_packages_to_install }}" state=present
    update_cache={{ always_update_cache }} cache_valid_time=3600
  when: >
    install_python_developer_packages is defined
    and install_python_developer_packages

- name: Developer | Install python modules
  pip: name={{ item }}
  with_items: "{{ pip_packages_to_install }}"
  when: install_pip_packages

- name: Developer | Install nvm
  include: nvm.yml
  when: (install_npm_packages or install_npm_iot_cloud_packages or install_nvm)

# - name: Developer | Install node.js packages
#   npm: pkg={{ item }} global=yes
#   with_items: "{{ npm_packages_to_install }}"
#   when: install_npm_packages

# - name: Developer | Install Cloud node.js packages
#   npm: pkg={{ item }} global=yes
#   with_items: "{{ npm_iot_cloud_packages_to_install }}"
#   when: install_npm_iot_cloud_packages

- name: Developer | Make directory for git repositories
  file: path={{ git_repositories_basedir }} state=directory
  when: install_git_repositories
  become: false

- name: Developer | Install git packages
  git: repo={{ item.repo }} dest={{ item.dest }}
  with_items: "{{ git_repositories_to_clone }}"
  become: false
  when: install_git_repositories
