---

- name: raspi-config | Update hostname
  command: raspi-config nonint do_hostname {{ inventory_hostname }}
  register: rpicfg_do_hostname

- name: raspi-config | Update memory split
  command: raspi-config nonint do_memory_split {{ rpicfg_memory_split }}
  when: rpicfg_memory_split is defined

- name: raspi-config | VNC server
  command: raspi-config nonint do_vnc {{ rpicfg_disable_vnc_server }}
  when: rpicfg_disable_vnc_server is defined

- name: raspi-config | SSH server
  command: raspi-config nonint do_ssh {{ rpicfg_disable_ssh_server }}
  when: rpicfg_disable_ssh_server is defined

- name: raspi-config | Configure I2C bus support
  command: raspi-config nonint do_i2c {{ rpicfg_disable_i2c }}
  when: rpicfg_disable_i2c is defined

- name: raspi-config | Configure SPI bus support
  command: raspi-config nonint do_spi {{ rpicfg_disable_spi }}
  when: rpicfg_disable_spi is defined

- name: raspi-config | Boot Behaviour
  command: raspi-config nonint do_boot_behaviour {{ rpicfg_boot_behaviour }}
  when: rpicfg_boot_behaviour is defined
  register: rpicfg_do_boot_behaviour
