---

- name: Package maintainance | Reboot
  command: /sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Package maintenance | Wait for Raspberry PI to come back
  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=30
  become: false
