---
# Ansible Playbook for maintaining bootstrapped Raspberry Pi

- hosts: raspberrypi-nodes
  roles:
    - raspbian-maintenance
  remote_user: "{{ ansible_user }}"
  become: true

- hosts: raspberrypi-wifi
  roles:
    - raspbian-wifi
  remote_user: "{{ ansible_user }}"
  become: true
