---
- name: Wi-Fi | Configure wpa_supplicant
  template:
    src:   etc/wpa_supplicant/wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart networking
  tags: [raspi_wifi]

- name: Wi-Fi | Start networking service
  service: name=networking state=started enabled=yes
  tags: [raspi_wifi, service]

- name: Wi-Fi | Reboot
  command: /sbin/shutdown -r +0 'Ansible Reboot triggered'
  async: 0
  poll: 0
  ignore_errors: true
  become: true

- name: Wi-Fi | Wait for Raspberry PI to come back
  local_action: >
    wait_for host={{ ansible_host }} state=started port=22 delay=50 timeout=120
  become: false

- name: Wi-Fi | Get IP address
  shell: "ip -o -4 addr show | awk -F '[ /]+' '/global/ {print $2,$4}'"
  register: hostname_ip

- name: Wi-Fi | Show IP addresses
  debug: msg="{{ hostname_ip.stdout.split('\n') }}"

- osx_say:
    msg: 'wi-fi configured'
    voice: Alex
  delegate_to: localhost
  become: false
