
---
- name: apt-cacher-ng | configuring apt caching (Client)
  template:
    src: 02proxy.j2
    dest: /etc/apt/apt.conf.d/02proxy
    owner: root
    group: root
    mode: 0644
  register: apt_caching_configured
  when: enable_apt_cacher_ng_proxy is defined and enable_apt_cacher_ng_proxy

- name: apt-cacher-ng | removing apt caching (Client)
  file:
    path: "{{ item }}"
    state: absent
  register: apt_caching_configured
  with_items:
    - /etc/apt/apt.conf.d/02proxy
  when: (enable_apt_cacher_ng_proxy is defined and not enable_apt_cacher_ng_proxy) or enable_apt_cacher_ng_proxy is not defined
